# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."shoko_server" = {
    image = "ghcr.io/shokoanime/server:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Etc/GMT-1";
    };
    volumes = [
      "/home/olivernix/shoko_server/shoko-config:/home/shoko/.shoko:rw"
      "/run/media/olivernix/16e95dc7-12da-47bc-90dd-4ec419d895e4/Monogatari Series:/mg:rw"
#     "/run/media/olivernix/16e95dc7-12da-47bc-90dd-4ec419d895e4/anime:/anime:rw"
    ];
    ports = [
      "8111:8111/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=shoko_server"
      "--network=shoko_server_default"
      "--shm-size=268435456"
    ];
  };
  systemd.services."podman-shoko_server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-shoko_server_default.service"
    ];
    requires = [
      "podman-network-shoko_server_default.service"
    ];
    partOf = [
      "podman-compose-shoko_server-root.target"
    ];
    wantedBy = [
      "podman-compose-shoko_server-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-shoko_server_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f shoko_server_default";
    };
    script = ''
      podman network inspect shoko_server_default || podman network create shoko_server_default
    '';
    partOf = [ "podman-compose-shoko_server-root.target" ];
    wantedBy = [ "podman-compose-shoko_server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-shoko_server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
