# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."shoko_server" = {
    image = "ghcr.io/shokoanime/server:latest";
    environment = {
      "PGID" = "";
      "PUID" = "";
      "TZ" = "Etc/GMT-1";
    };
    volumes = [
      "/home/olivernix/shoko/shoko-config:/home/shoko/.shoko:rw"
      "/media/Monogatari Series:/mg:rw"
      "/media/anime:/anime:rw"
    ];
    ports = [
      "8111:8111/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=shoko_server"
      "--network=shoko_default"
      "--shm-size=268435456"
    ];
  };
  systemd.services."docker-shoko_server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-shoko_default.service"
    ];
    requires = [
      "docker-network-shoko_default.service"
    ];
    partOf = [
      "docker-compose-shoko-root.target"
    ];
    wantedBy = [
      "docker-compose-shoko-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-shoko_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f shoko_default";
    };
    script = ''
      docker network inspect shoko_default || docker network create shoko_default
    '';
    partOf = [ "docker-compose-shoko-root.target" ];
    wantedBy = [ "docker-compose-shoko-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-shoko-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
