# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3da1ca60-5046-4678-93d3-a9a41466e845";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/3da1ca60-5046-4678-93d3-a9a41466e845";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/49c62222-ded2-49da-b5a3-61ca4a86707c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E299-A111";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/3da1ca60-5046-4678-93d3-a9a41466e845";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/3da1ca60-5046-4678-93d3-a9a41466e845";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/3da1ca60-5046-4678-93d3-a9a41466e845";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/disk/by-uuid/3da1ca60-5046-4678-93d3-a9a41466e845";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
